# This is the pipeline manifest file.
# It routes GitHub events to the correct pipeline YAML.
triggers:
  # Trigger for pushes to the main branch
  - on: push
    branches:
      - main
    path: .nopsai/main-pipeline.yaml

  # Trigger for pushes to any feature branch
  - on: push
    branches:
      - 'test-**'
    path: .nopsai/branch-pipeline.yaml

  # Trigger for new pull requests
  - on: pull_request
    path: .nopsai/main-pipeline.yaml

  # Trigger for creating a new tag
  - on: create # This event is for creating branches or tags
    tags:
      - 'v*.*.*'
    path: .nopsai/release-pipeline.yaml
