# This is the pipeline manifest file.
# It routes GitHub events to the correct pipeline YAML.
triggers:
  # Trigger for pushes to the main branch
  - on: push
    branches:
      - main
    paths: 
      - main-pipeline.yaml
      - include.yaml
    environment: prod
    
  # Trigger for pushes to any feature branch
  - on: push
    branches:
      - 'test-**'
    paths: branch-pipeline.yaml

  # Trigger for new pull requests
  - on: pull_request
    paths: main-pipeline.yaml
