# This is the pipeline manifest file.
# It routes GitHub events to the correct pipeline YAML.
triggers:
  # Trigger for pushes to the main branch
  - on: push
    branches:
      - main
    pipelines:
      - path: .nopsai/main-pipeline.yaml
      - path: .nopsai/include.yaml
      - url: 'https://github.com/hosein-yousefii/pre-nopsai/blob/main/sample-pipeline/5-pipeline.yaml'
        provider: github
    environment: prod
    
  # Trigger for pushes to any feature branch
  - on: push
    branches:
      - '**-test'
    pipelines: 
      - path: .nopsai/branch-pipeline.yaml

  # Trigger for new pull requests
  - on: pull_request
    pipelines: 
      - path: .nopsai/main-pipeline.yaml
