# This is the pipeline manifest file.
# It routes GitHub events to the correct pipeline YAML.
triggers:
  # Trigger for pushes to the main branch
  - on: push
    branches:
      - main
    pipelines:
      - main-pipeline.yaml
      - include.yaml      
    scope: prod

  # Trigger for pushes to any feature branch
  - on: push
    branches:
      - '*-test'
    pipelines: 
      - branch-pipeline.yaml

  # Trigger for new pull requests
  - on: pull_request
    pipelines: 
      - main-pipeline.yaml
